### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by arcanis** [elliott-wen/browservm.js#1]
Hey, kudos for releasing this! I've been following a lot of similar projects, it's nice to see one built upon qemu.

One question I have is regarding networking: I noticed you mentioned having an experimental support for it, but I haven't found to try it out. I ran `wget http://example.org` but to no avail (even the networking tab didn't mention anything happening behind the hood). Is there something special needed to make it work?

**Comment by elliott-wen** [comment]
Hello.

We did have a virtio network driver, which can receive and send network
packets. Check device.js

https://github.com/elliott-wen/browservm.js/blob/4b97786bd01646cca22006cc8a9eafab9447a887/device.js#L136

It is a stub function so far. You need to decide what to do with the
packets.

Cheers
Elliott

Maël Nison <notifications@github.com> 于2021年1月22日周五 下午10:09写道：

**Comment by arcanis** [comment]
Perfect, thanks!
