### ISSUE TITLE
Base Linux configuration

### ISSUE THREAD

**Issue by arcanis** [elliott-wen/browservm.js#2]
Trying to load a custom buildroot image fails with:

```
[    0.230518] VFS: Mounted root (ext2 filesystem) on device 254:0.
[    0.230528] devtmpfs: mounted
[    0.230530] Freeing unused kernel image (initmem) memory: 248K
[    0.230536] Write protecting kernel text and read-only data: 5524k
[    0.230539] Run /sbin/init as init process
FATAL: kernel too old
[    0.230654] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    0.230656] CPU: 0 PID: 1 Comm: init Not tainted 5.8.18 #36
```

This happens even when using musl, which I find surprising...

I tried rebuilding a kernel, but I found that tricky (at least when you've never done it before), since it's not clear which parameters are important. In my case for instance, any kernel I build fails with errors the like of:

```
---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0) ]---
```

Can you share the exact `.config` file you've used to build the kernel image, if only as a base?

Side question: do I need to tweak the `virtio_mmio.device` entries when updating the kernel? From the look of the constants the main ones are `MAX_KERNEL_SIZE` for the kernel and `HARDDISK_CAP` for the image, but I'm not sure about the mmio table, whether it should "just work" or there are modifications to make.

**Comment by elliott-wen** [comment]
I have updated the repo with Linux configuration (5.5.18) and buildroot
configuration.

I dont think you need to tweak the mmio device addresses. Unless you are
expanding your main memory too much.

The code is quite messy, feel free to clean it.

Cheers
Elliott

Maël Nison <notifications@github.com> 于2021年1月23日周六 上午3:39写道：

**Comment by arcanis** [comment]
Perfect, thanks! I've managed to fix it on my end by selecting `systemd` as init system. Not sure why the default didn't work 🤔
